### PR TITLE
Fix CPU reporting

### LINKED ISSUE #68: CPU Reporting Broken
CPU reporting seems to be broken on both the main branch and add_collector_service. This is happening in both Desktop 24.04 and WSL 24.04.

From what I can tell, it is an issue with parsing the output of `lscpu -J`.

Currently, the filter being used goes uses the io reader to go line by line, trying to match each line with the regex. However, this means it never matches the regex which is looking for something along the lines of `{"field": "<key>", "data": "<value>"}`, however in the output, these will be split up into different lines. (This regex seems too strict anyways, and even if everything were on one line, would fail to capture cases where there is info after the data field such as `"data": "<value>", "children": [...` such as for CPU(s).

image

To fix this, since we need the field and data paired together, it may be easier to instead of using the Json format, just scan line by line from the human-readable response, trim the line, split at `: ` and try to match the left with a known key via a switch.

image

Alternatively, do a proper parsing of the json return

### PR DESCRIPTION
**Pull request by hk21702**
Closes #68 

Fixes CPU reporting by implementing proper JSON parsing and implementing it for lscpu -J. 
Tests have been updated to now better reflect `lscpu -J'`s output (Whitespace, new lines, and children)

For other things that could also be in JSON format, it should be fairly easy to add onto json.go with the expected structure and use `parseJson`

parseJSON uses marshalling instead of a decoder to handle the case where the command provides a valid JSON output, but fails right after.

### CODE REVIEW

File: internal/metrics/cmd.go [hunk 1]
```diff
@@ -40,45 +40,56 @@ func (m Metrics) getCPU() cpuInfo {
...
-		case "Hypervisor vendor:":
-			c.Hypervisor = v
-		case "Virtualization type:":
-			c.VirtualizationType = v
+	if err != nil {
+		log.Infof("Couldn't get CPU info: "+utils.ErrFormat, err)
+		return cpuInfo{}
+	}
+
+	lscpu := result.(*Lscpu)
```
Comment (didrocks) [inline internal/metrics/cmd.go:50]: Here, if the casting for `$reasons` fails, the program will panic, which is what we always try to avoid in Go. It would be better to assign the success check when casting with `, ok` and check for the `ok` value to return an error.
Typically:

```
lscpu, ok := result.(*Lscpu)
if !ok {
  log.Infof("Couldn't get CPU info, could not convert to a valid Lscpu entry: %v", result)
}

File: internal/metrics/cmd.go [hunk 2]
```diff
@@ -40,45 +40,56 @@ func (m Metrics) getCPU() cpuInfo {
...
+
+	// helper recursive function to populate the cpuInfo struct
```
Comment (didrocks) [inline internal/metrics/cmd.go:52]: If you are creating a recursive function for that, while the closure works, in term of code complexity I would appreiciate if you can extract `populateCpuInfo` as its own separate function.

File: internal/metrics/json.go [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+	Field    string       `json:"field"`
+	Data     string       `json:"data"`
+	Children []LscpuEntry `json:"children,omitempty"`
+}
+
+type Lscpu struct {
+	Lscpu []LscpuEntry `json:"lscpu"`
+}
+
+func parseJSON(r io.Reader, structPtr interface{}) (interface{}, error) {
```
Comment (didrocks) [inline internal/metrics/json.go:20]: you should start using `any` which is way more recent than this code, true, but for empty interface, this is more idiomatic in the meaning.

I don’t really like the `Ptr` suffix to the struct and as the function is rather small, I would align with the Go standard library with just `v`: https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/encoding/json/decode.go;l=97

Btw, did you notice they converted their code to any? :p

**Review by didrocks — CHANGES_REQUESTED** [review]
Excellent work! I’m glad that you figured it out in this ancient, rusty, Go code which would definitively need some love!

I have few changes for requests, but in general, this looks very good to me.

On your general comment: I agree with you that we could in the future modernize it, but let’s see what’s the result on the telemetry checks, to see if this is a dimension worth pushing or if we should invest in a more modern stack.

Tell me once you are done with the small requested changes!

File: internal/metrics/json.go (hunk 3 above)
Comment (hk21702) [reply internal/metrics/json.go:20]: I think this code is still 1.13 and `any` isn't supported in this context yet! Would you like me to maybe convert it?

Comment (didrocks) [reply internal/metrics/json.go:20]: yes, feel free to bump the Go version!

File: internal/metrics/cmd.go (hunk 1 above)
Comment (hk21702) [reply internal/metrics/cmd.go]: Done!

File: internal/metrics/cmd.go (hunk 2 above)
Comment (hk21702) [reply internal/metrics/cmd.go]: Done!

File: internal/metrics/cmd.go [hunk 4]
```diff
@@ -35,6 +35,45 @@ func (m Metrics) getGPU() []gpuInfo {
 	return gpus
 }
 
+// helper recursive function for getCPU to populate the cpuInfo struct
```
Comment (didrocks) [inline internal/metrics/cmd.go:38]: even if this is not an exported functions (and I se that this project doesn’t even have linter CI setup… See how old it is), the format for comments are `// <functionname> does something.` (Note the finale dot here).

I’m sure this code is full of counter example, but do you mean updating to it so that at least the new code follows this pattern?

File: internal/metrics/json.go (hunk 3 above)
Comment (hk21702) [reply internal/metrics/json.go]: Done!

**Review by didrocks — CHANGES_REQUESTED** [review]
Excellent thanks! One minor thing on coment and then, we are good to merge :)

File: internal/metrics/cmd.go (hunk 4 above)
Comment (hk21702) [reply internal/metrics/cmd.go]: It should be fixed now!

**Review by didrocks — APPROVED** [review]
Great work on old code base :) We’ll discuss how we’ll SRU it to existing releases in a future pulse.

Thanks again for your help here!
